name: CI/CD workflow for HTML project with SonarQub

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  code_scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      with:
        projectBaseDir: .
        args: >
          -Dsonar.organization=my-org
          -Dsonar.projectKey=my-html-project
          -Dsonar.sources=.
          -Dsonar.exclusions=**/*.java
          -X # Enable detailed logging
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
